# Database settings.
database:

  # the name of your JDBC driver
  driverClass: ${DB_DRIVER:-org.postgresql.Driver}

  # the username
  user: ${DB_USERNAME:-postgres}

  # the password
  password: ${DB_PASSWORD:-password}

  # the JDBC URL
  url: ${DB_URL:-jdbc:postgresql://localhost:5432/budget}

  # any properties specific to JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: ${DB_DIALECT:-io.smartbudget.dialect.CustomPostgreSQLDialect}
    hibernate.format_sql: true

  validationQuery: ${DB_VALIDATE_QUERY:-SELECT 1}

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false

assets:
  overrides:
    /app: src/main/resources/app

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'io.budgetapp' to DEBUG.
    io.budgetapp: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console

categories:
  - name: Income
    type: INCOME
  - name: Home
    type: EXPENDITURE
  - name: Transportation
    type: EXPENDITURE
  - name: Health
    type: EXPENDITURE
  - name: Charity/Gifts
    type: EXPENDITURE
  - name: Daily Living
    type: EXPENDITURE
  - name: Entertainment
    type: EXPENDITURE
  - name: Savings
    type: EXPENDITURE
  - name: Obligations
    type: EXPENDITURE
  - name: Miscellaneous
    type: EXPENDITURE

budgets:
  Income:
    - name: Wages & Tips
    - name: Interest Income
    - name: Dividends
    - name: Gifts Received
    - name: Refunds/Reimbursements
    - name: Transfer From Savings
  Home:
    - name: Mortgage/Rent
    - name: Home/Rental Insurance
    - name: Electricity
    - name: Gas/Oil
    - name: Water/Sewer/Trash
    - name: Phone
    - name: Cable/Satellite
    - name: Internet
    - name: Furnishings/Appliances
    - name: Maintenance/Supplies
  Transportation:
    - name: Vehicle Payments
    - name: Auto Insurance
    - name: Fuel
    - name: Bus/Taxi/Train Fare
    - name: Repairs
    - name: Registration/License
  Health:
    - name: Health Insurance
    - name: Doctor/Dentist
    - name: Medicine/Drugs
    - name: Health Club Dues
    - name: Life Insurance
    - name: Veterinarian/Pet Care
  Charity/Gifts:
    - name: Gifts Given
    - name: Charitable Donations
    - name: Religious Donations
  Subscription:
    - name: Newspaper
    - name: Magazines
    - name: Dues/Memberships
  Daily Living:
    - name: Groceries
    - name: Personal Supplies
    - name: Clothing
    - name: Cleaning
    - name: Education/Lessons
    - name: Dining/Eating Out
    - name: Salon/Barber
    - name: Pet Food
  Entertainment:
    - name: Videos/DVDs
    - name: Music
    - name: Games
    - name: Rentals
    - name: Movies/Theater
    - name: Concerts/Plays
    - name: Books
    - name: Hobbies
    - name: Film/Photos
    - name: Sports
    - name: Outdoor Recreation
    - name: Toys/Gadgets
    - name: Vacation/Travel
  Savings:
    - name: Emergency Fund
    - name: Transfer to Savings
    - name: Retirement (401k, IRA)
    - name: Investments
    - name: Education
  Obligations:
    - name: Student Loan
    - name: Other Loan
    - name: Credit Cards
    - name: Alimony/Child Care
    - name: Federal Taxes
    - name: State/Local Taxes
  Miscellaneous:
    - name: Bank Fees
    - name: Postage
